baseURL = 'https://victorbarreto.dev/'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-US'
defaultContentLanguage = 'en'
theme = 'enchanted-lowkey'
title = 'Victor Barreto'
enableRobotsTXT = true
summaryLength = 15
pagerSize  = 5


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/posts/:filename/"
  categories = "/categories/:slug/"
[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content"
    weight = 1
  [languages.pt-br]
    languageName = "Português"
    contentDir = "content/br"
    weight = 2