# Homepage Config
isSinglePage = true

# Meta Config
description = "Hello"

# Header Configuration
avatar = "img/1721611881759.jpg"

#favicon
favicon = "icons/favicon.ico"

# disqus is a comment system. see https://disqus.com
disqusShortname = ""

[emoji]
enableEmoji = true

# giscus is a comment system based on GitHub Discussions. see https://giscus.app
[giscus]       
    enable = true
    repo = "victorbarretodev/victorbarreto.dev"
    repoId = "R_kgDOOKBr3g"
    category = "Blog"
    categoryId = "DIC_kwDOOKBr3s4CoKLM"
    mapping = "pathname"  # comment value is the default value
    # strict = 0
    reactionsEnabled = 1
    # emitMetadata = 0
    inputPosition = "top"
    # theme = "light"
    lang = "en"
    lazyLoading = true